// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Users__CpfValidatorController from "./users/cpf_validator_controller"
application.register("users-cpf-validator", Users__CpfValidatorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import Users__UpdatePasswordModalController from "./users/update_password_modal_controller"
application.register("users-update-password-modal", Users__UpdatePasswordModalController)
