version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "1020:3000"
    depends_on:
      - db
    env_file: .env

volumes:
  db_data:
